#!/usr/bin/env python
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import getopt
import json
import sys
import os


def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], '', [
            'reviewboard=', 'bugzilla='
        ])
        if len(args) == 0:
            raise getopt.GetoptError("missing state-file")
        state_filename = args[0]
    except getopt.GetoptError as err:
        print(str(err))
        sys.exit(2)

    if os.path.isfile(state_filename):
        with open(state_filename) as state_file:
            state = json.load(state_file)
    else:
        state = {}

    for o, a in opts:
        state[o[2:]] = a
    with open(state_filename, 'w') as state_file:
        json.dump(state, state_file)

if __name__ == "__main__":
    main()
