# XXX document these
REVIEWBOARD_PORT: 8080
BUGZILLA_PORT: 8081

# enable verbose vagrant output
VERBOSE: false

# configure port forwarding for the ldap server
# not required for normal operations, but can be useful for debugging
FORWARD_LDAP: true
