
# these are the ports review board, bugzilla, and ssh will use locally
# ie. if REVIEWBOARD_PORT is set to 8080, you'd use http://localhost:8080/ to
# connect to it.
# these defaults should work for most people, however you can change them if
# they conflict with something already running on your workstation.

REVIEWBOARD_PORT: 8080
BUGZILLA_PORT: 8081
SSH_PORT: 8082
HGWEB_PORT: 8083

# enable verbose vagrant output
VERBOSE: false

# configure port forwarding for the ldap server
# not required for normal operations, but can be useful for debugging
FORWARD_LDAP: false
