#!/usr/bin/env python
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import getopt
import json
import os
import sys


def get_ip_address(ifname):
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    return socket.inet_ntoa(fcntl.ioctl(
        s.fileno(),
        0x8915,  # SIOCGIFADDR
        struct.pack('256s', ifname[:15])
    )[20:24])


def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], '', [
            'reviewboard=', 'bugzilla=', 'ssh=', 'hgweb='
        ])
        if len(args) == 0:
            raise getopt.GetoptError("missing state-file")
        state_filename = args[0]
    except getopt.GetoptError as err:
        print(str(err))
        sys.exit(2)

    if os.path.isfile(state_filename):
        with open(state_filename) as state_file:
            state = json.load(state_file)
    else:
        state = {}

    for o, a in opts:
        state[o[2:]] = a

    with open(state_filename, 'w') as state_file:
        json.dump(state, state_file, indent=2, sort_keys=True)

if __name__ == "__main__":
    main()
