---

- name: check for existing instance
  stat: path=/bugzilla/checksetup_answers.txt
  ignore_errors: true
  register: existing_bmo

- name: install httpd vhost config
  template: src=vhost.conf.j2
            dest=/etc/httpd/conf.d/bugzilla.conf
  when: existing_bmo.stat.exists == false

- name: create checksetup_answers.txt
  copy: src=checksetup_answers.txt
        dest=/bugzilla/checksetup_answers.txt
  when: existing_bmo.stat.exists == false

- name: create set-param.pl
  copy: src=set-param.pl
        dest=/bugzilla/scripts/set-param.pl
  when: existing_bmo.stat.exists == false

- name: create mysql user
  mysql_user: name=bugs
              password=bugs
              state=present
              priv=bugs.*:ALL
  when: existing_bmo.stat.exists == false

- name: create mysql database
  mysql_db: name=bugs
            encoding=utf8
            state=present
  when: existing_bmo.stat.exists == false

- name: checksetup (1/2)
  command: perl checksetup.pl checksetup_answers.txt
  args:
      chdir: /bugzilla
  when: existing_bmo.stat.exists == false

- name: checksetup (2/2)
  command: perl checksetup.pl checksetup_answers.txt
  args:
      chdir: /bugzilla
  when: existing_bmo.stat.exists == false

- name: generate bmo data
  command: perl docker/generate_bmo_data.pl admin@example.com
  args:
      chdir: /bugzilla
  when: existing_bmo.stat.exists == false

- name: set params
  command: perl scripts/set-param.pl {{ item.name }} {{ item.value }}
  args:
    chdir: /bugzilla
  with_items:
    - { name: 'auth_delegation', value: '1' }
    - { name: 'bugzilla_version', value: 'BMO-MozReview' }
    - { name: 'mail_delivery_method', value: 'None' }
    - { name: 'mozreview_auth_callback_url', value: 'http://localhost:8080/mozreview/bmo_auth_callback/' }
    - { name: 'mozreview_base_url', value: 'http://localhost:8080/' }
    - { name: 'urlbase', value: 'http://localhost:{{ bugzilla_port }}/' }
  when: existing_bmo.stat.exists == false

- name: restart httpd
  service: name=httpd
           state=restarted
  when: existing_bmo.stat.exists == false

- name: create test bugs
  command: /src/dev/scripts/create-bugs 10 Firefox General
  when: existing_bmo.stat.exists == false
